# Generated by Django 5.2.6 on 2025-09-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsheet',
            name='on_duty_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='logsheet',
            name='driving_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='logsheet',
            name='rest_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
